import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, Lock } from "lucide-react";
import { Link } from "react-router-dom";
import { Avatar } from "@/components/ui/Avatar";
import { useAdmission } from "@/state/AdmissionProvider";
import { useSession } from "@/state/SessionProvider";

const inputClass = "mt-2 block h-11 w-full rounded-xl border border-line-strong bg-white px-3 text-sm text-ink outline-none focus:border-brand-500 disabled:bg-canvas";

export function StudentProfile() {
  const { account } = useSession();
  const { state, update } = useAdmission();
  const [guardianName, setGuardianName] = useState(state.guardian?.name ?? "");
  const [relationship, setRelationship] = useState(state.guardian?.relationship ?? "");
  const [guardianEmail, setGuardianEmail] = useState(state.guardian?.email ?? "");
  const [city, setCity] = useState(state.profile?.city ?? "");
  const [goal, setGoal] = useState(state.profile?.goal ?? "");
  const [saved, setSaved] = useState<"guardian" | "profile" | null>(null);

  return <div className="mx-auto max-w-2xl space-y-7"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-brand-700 hover:underline"><ArrowLeft className="size-4" /> Back to overview</Link><header className="flex items-center gap-4"><Avatar name={account?.name ?? "Student"} size="xl" ring /><div><p className="text-xs font-bold uppercase tracking-[.15em] text-brand-700">Your account</p><h1 className="mt-1 text-title text-ink">{account?.name}</h1><p className="text-sm text-muted">{account?.email}</p></div></header>
    <section id="guardian" aria-labelledby="guardian-heading" className="scroll-mt-24 rounded-[26px] border border-line bg-white p-6 shadow-card sm:p-8"><p className="text-xs font-bold uppercase tracking-[.15em] text-brand-700">Step 01 / Before admission</p><h2 id="guardian-heading" className="mt-2 text-xl font-extrabold text-ink">Onboard your guardian</h2><p className="mt-2 text-sm text-muted">Add a trusted parent or guardian to your account details. They are not contacted in this preview.</p><form onSubmit={(event) => { event.preventDefault(); update({ guardian: { name: guardianName.trim(), relationship: relationship.trim(), email: guardianEmail.trim().toLowerCase() } }); setSaved("guardian"); }} className="mt-6 grid gap-4"><label className="text-xs font-bold text-ink">Guardian's name<input required value={guardianName} onChange={(event) => setGuardianName(event.target.value)} className={inputClass} placeholder="Full name" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-ink">Relationship<input required value={relationship} onChange={(event) => setRelationship(event.target.value)} className={inputClass} placeholder="Parent, aunt, uncle…" /></label><label className="text-xs font-bold text-ink">Email address<input required type="email" value={guardianEmail} onChange={(event) => setGuardianEmail(event.target.value)} className={inputClass} placeholder="guardian@example.com" /></label></div><div className="flex flex-wrap items-center gap-3"><button type="submit" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-brand-500 px-5 text-sm font-bold text-white hover:bg-brand-600">Save guardian <ArrowRight className="size-4" /></button>{saved === "guardian" && <p role="status" className="inline-flex items-center gap-1.5 text-sm font-semibold text-success"><Check className="size-4" /> Saved on this device</p>}</div></form></section>
    <section id="complete" aria-labelledby="profile-heading" className="scroll-mt-24 rounded-[26px] border border-line bg-white p-6 shadow-card sm:p-8"><p className="text-xs font-bold uppercase tracking-[.15em] text-brand-700">Step 05 / Before admission</p><h2 id="profile-heading" className="mt-2 text-xl font-extrabold text-ink">Complete your profile</h2><p className="mt-2 text-sm text-muted">Your city and the kind of work you want to explore can change as you learn.</p>{!state.interviewComplete && <p className="mt-5 inline-flex items-center gap-2 rounded-full bg-canvas px-3 py-2 text-xs font-semibold text-muted"><Lock className="size-3.5" /> Opens after the registration interview</p>}<form onSubmit={(event) => { event.preventDefault(); update({ profile: { city: city.trim(), goal: goal.trim() } }); setSaved("profile"); }} className="mt-6 grid gap-4"><label className="text-xs font-bold text-ink">City<input required disabled={!state.interviewComplete} value={city} onChange={(event) => setCity(event.target.value)} className={inputClass} placeholder="Where you live" /></label><label className="text-xs font-bold text-ink">A role or field you'd like to explore<input required disabled={!state.interviewComplete} value={goal} onChange={(event) => setGoal(event.target.value)} className={inputClass} placeholder="It is okay if you are still unsure" /></label><div className="flex flex-wrap items-center gap-3"><button type="submit" disabled={!state.interviewComplete} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-brand-500 px-5 text-sm font-bold text-white hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-45">Save profile <ArrowRight className="size-4" /></button>{saved === "profile" && <p role="status" className="inline-flex items-center gap-1.5 text-sm font-semibold text-success"><Check className="size-4" /> Saved on this device</p>}</div></form></section>
  </div>;
}
