// Generated by scripts/fetch-3d-assets.mjs — do not edit by hand.
// Run `pnpm assets:3d` after changing scripts/emoji-manifest.mjs.

/** Every 3D illustration available in public/art/3d/. */
export type Art3DName =
  | "bank"
  | "bar-chart"
  | "bell"
  | "bolt"
  | "books"
  | "brain"
  | "briefcase"
  | "bulb"
  | "calendar"
  | "chart-up"
  | "check"
  | "clapper"
  | "clipboard"
  | "compass"
  | "construction"
  | "credit-card"
  | "crown"
  | "dress"
  | "energy"
  | "fire"
  | "fork-knife"
  | "gear"
  | "gem"
  | "gift"
  | "glowing-star"
  | "graduation-cap"
  | "guardian"
  | "handshake"
  | "hourglass"
  | "id-card"
  | "key"
  | "laptop"
  | "locked"
  | "magnifier"
  | "medal"
  | "memo"
  | "money-bag"
  | "office"
  | "package"
  | "party"
  | "people"
  | "pushpin"
  | "rocket"
  | "satellite"
  | "scales"
  | "seedling"
  | "sheaf"
  | "shield"
  | "soccer"
  | "speech"
  | "star"
  | "stethoscope"
  | "target"
  | "telescope"
  | "tools"
  | "trophy"
  | "truck"
  | "unlocked"
  | "video-camera"
  | "world-map";

export const ART_3D_NAMES: readonly Art3DName[] = [
  "bank",
  "bar-chart",
  "bell",
  "bolt",
  "books",
  "brain",
  "briefcase",
  "bulb",
  "calendar",
  "chart-up",
  "check",
  "clapper",
  "clipboard",
  "compass",
  "construction",
  "credit-card",
  "crown",
  "dress",
  "energy",
  "fire",
  "fork-knife",
  "gear",
  "gem",
  "gift",
  "glowing-star",
  "graduation-cap",
  "guardian",
  "handshake",
  "hourglass",
  "id-card",
  "key",
  "laptop",
  "locked",
  "magnifier",
  "medal",
  "memo",
  "money-bag",
  "office",
  "package",
  "party",
  "people",
  "pushpin",
  "rocket",
  "satellite",
  "scales",
  "seedling",
  "sheaf",
  "shield",
  "soccer",
  "speech",
  "star",
  "stethoscope",
  "target",
  "telescope",
  "tools",
  "trophy",
  "truck",
  "unlocked",
  "video-camera",
  "world-map",
];
